name: Deploy to S3

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
      
    - name: Install dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        else
          echo "No package.json found, skipping npm install"
        fi
        
    - name: Build project
      run: |
        # Para proyectos simples, solo copiar archivos
        mkdir -p dist
        cp -r src/* dist/
        
        # Para proyectos con build (descomenta si necesitas):
        # npm run build
        
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Verify AWS connection
      run: |
        aws sts get-caller-identity
        aws s3 ls s3://${{ secrets.S3_BUCKET_NAME }} || echo "Bucket exists"
        
    - name: Deploy to S3
      run: |
        echo "Uploading files to S3..."
        aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} \
          --delete \
          --exact-timestamps \
          --exclude ".DS_Store" \
          --exclude "*.md"
          
    - name: 🏷️ Set cache headers
      run: |
        # CSS y JS con cache largo
        aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }} s3://${{ secrets.S3_BUCKET_NAME }} \
          --recursive \
          --exclude "*" \
          --include "*.css" \
          --include "*.js" \
          --metadata-directive REPLACE \
          --cache-control "max-age=31536000"
          
        # HTML sin cache
        aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }} s3://${{ secrets.S3_BUCKET_NAME }} \
          --recursive \
          --exclude "*" \
          --include "*.html" \
          --metadata-directive REPLACE \
          --cache-control "no-cache"
          
    - name:  Show website URL
      run: |
        echo "" Deployment completed!"
        echo "Website URL: http://${{ secrets.S3_BUCKET_NAME }}.s3-website-${{ secrets.AWS_REGION }}.amazonaws.com"